version: "3.8"

services:
  db:
    image: mysql:latest
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - ./wp:/var/www/html
    ports:
      - "8880:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: database
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
